//
//  Storeage+TestResults.swift
//  BCVaccineCard
//
//  Created by Amir on 2021-11-29.
//

import Foundation

extension StorageService {
    
    
    /// Store a test result from a HealthGateway response
    /// - Parameter gateWayResponse: codable response object from Health Gateway
    /// - Returns: String id of record if stored successfully
    public func saveTestResult(phn: String, birthdate: Date, gateWayResponse: GatewayTestResultResponse) -> String? {
        let id = gateWayResponse.md5Hash() ?? UUID().uuidString
        
        guard let context = managedContext else {return nil}
        let model = CovidLabTestResult(context: context)
        
        model.id = gateWayResponse.md5Hash()
        model.phn = phn
        model.birthday = birthdate
        model.user = fetchUser()
        
        var testResults: [TestResult] = []
        guard let records = gateWayResponse.resourcePayload?.records else { return nil }
        for record in records {
            if let resultModel = saveTestResult(
                resultId: id,
                patientDisplayName: record.patientDisplayName,
                lab: record.lab,
                reportId: record.reportId,
                collectionDateTime: record.collectionDateTimeDate,
                resultDateTime: record.resultDateTimeDate,
                testName: record.testName,
                testType: record.testType,
                testStatus: record.testStatus,
                testOutcome: record.testOutcome,
                resultTitle: record.resultTitle,
                resultDescription: record.resultDescription,
                resultLink: record.resultLink) {
                
                testResults.append(resultModel)
                model.addToResults(resultModel)
            }
        }
        
        do {
            try context.save()
            self.notify(event: StorageEvent(event: .Save, entity: .CovidLabTestResult, object: model))
            return id
        } catch let error as NSError {
            print("Could not save. \(error), \(error.userInfo)")
            return nil
        }
    }
    
    
    /// Store a test result
    /// - Returns: String id of record if stored successfully
    private func saveTestResult(
        resultId: String,
        patientDisplayName: String?,
        lab: String?,
        reportId: String?,
        collectionDateTime: Date?,
        resultDateTime: Date?,
        testName: String?,
        testType: String?,
        testStatus: String?,
        testOutcome: String?,
        resultTitle: String?,
        resultDescription: [String]?,
        resultLink: String?) -> TestResult? {
            guard let context = managedContext else {return nil}
            let testResult = TestResult(context: context)
            testResult.id = reportId
            testResult.patientDisplayName = patientDisplayName
            testResult.lab = lab
            testResult.reportId = reportId
            testResult.collectionDateTime = collectionDateTime
            testResult.resultDateTime = resultDateTime
            testResult.testName = testName
            testResult.testType = testType
            testResult.testStatus = testStatus
            testResult.testOutcome = testOutcome
            testResult.resultTitle = resultTitle
            testResult.resultDescription = resultDescription
            testResult.resultLink = resultLink
            do {
                try context.save()
                self.notify(event: StorageEvent(event: .Save, entity: .TestResult, object: testResult))
                return testResult
            } catch let error as NSError {
                print("Could not save. \(error), \(error.userInfo)")
                return nil
            }
        }
    
    
    /// delete a test result for given id
    /// - Parameter id: id of record. this can be the report id or the id generated by during storage (TestResult.id)
    func deleteTestResult(id: String) {
        guard let context = managedContext else {return}
        do {
            let tests = try context.fetch(CovidLabTestResult.fetchRequest())
            guard let item = tests.filter({ ($0.id == id) }).first else {return}
            context.delete(item)
            try context.save()
            self.notify(event: StorageEvent(event: .Delete, entity: .CovidLabTestResult, object: item))
        } catch let error as NSError {
            print("Could not delete. \(error), \(error.userInfo)")
            return
        }
    }
    
    /// Returns all test results stored for user
    /// - Parameter userId: User id. if left empty, the results results for the currently authenticated user.
    /// - Returns: All Test results stored for the given user
    func fetchTestResults(for userId: String? = AuthManager().userId()) -> [CovidLabTestResult] {
        guard let context = managedContext else {return []}
        do {
            let users = try context.fetch(User.fetchRequest())
            guard let current = users.filter({$0.userId == userId}).first else {return []}
            return current.testResultArray
        } catch let error as NSError {
            print("Could not fetch. \(error), \(error.userInfo)")
            return []
        }
    }
    
    
    /// Find the stored test record that is likely the one from the response:
    /// - Parameter gateWayResponse: gateway test result response
    /// - Returns: Stored CovidLabTestResult object that matches the response
    func findExistingResult(gateWayResponse: GatewayTestResultResponse) -> CovidLabTestResult? {
        let tests = fetchTestResults()
        guard let responseTestIds = gateWayResponse.resourcePayload?.records.map({$0.reportId}) else {
            return nil
        }
        // Loop through stored tests
        for test in tests {
            let results = test.resultArray
            // Cache ids of stored results in this test
            var storedTestIds = results.map({$0.reportId})
            // Loop through the ids in the gateway response
            // and remove ids in storedTestIds that are also in responseTestIds
            for recordId in responseTestIds {
                if let index = storedTestIds.firstIndex(of: recordId) {
                    storedTestIds.remove(at: index)
                }
            }
            
            // now if responseTestIds is empty, they were all contained in the response.
            if storedTestIds.isEmpty && !responseTestIds.isEmpty {
                return test
            }
        }
        return nil
    }
    
    /// Update a test result from a HealthGateway response
    /// - Parameter gateWayResponse: codable response object from Health Gateway
    func updateTestResult(gateWayResponse: GatewayTestResultResponse, completion: @escaping(Bool)->Void) {
        guard
            let context = managedContext,
            let existing = findExistingResult(gateWayResponse: gateWayResponse),
            let existingId = existing.id,
            // Temp cache: when we refactor storage, this information will be stored under user and wont be necessary to do this here
            let phn = existing.phn,
            let birthday = existing.birthday
        else {return completion(false)}
        
        
        // Delete existing
        deleteTestResult(id: existingId)
        // Store the new one.
        let res = saveTestResult(phn: phn, birthdate: birthday, gateWayResponse: gateWayResponse)
        return completion(res != nil)
    }
}
