//
//  Storeage+TestResults.swift
//  BCVaccineCard
//
//  Created by Amir on 2021-11-29.
//

import Foundation

extension StorageService {
    
    
    /// Store a test result from a HealthGateway response
    /// - Parameter gateWayResponse: codable response object from Health Gateway
    /// - Returns: String id of record if stored successfully
    public func saveTestResult(gateWayResponse: GatewayTestResultResponse) -> String? {
        let userId = AuthManager().userId()
        let id = gateWayResponse.md5Hash() ?? UUID().uuidString
        
        /**
                TODO:
                    When GatewayTestResultResponse is updated, Here we will first store the parent test object and then
                         for each teast in that reponse, we will call saveTestResult
         */
        
        // 1) for each result in the reponse save the test
        var testResults: [TestResult] = []
        /*
        for whatever in gateWayResponse.whatever {
            if let resultModel = saveTestResult(
                   resultId: id,
                   patientDisplayName: gateWayResponse.patientDisplayName,
                   lab: gateWayResponse.lab,
                   reportId: gateWayResponse.reportId,
                   collectionDateTime: gateWayResponse.collectionDateTime,
                   resultDateTime: gateWayResponse.resultDateTime,
                   testName: gateWayResponse.testName,
                   testType: gateWayResponse.testType,
                   testStatus: gateWayResponse.testStatus,
                   testOutcome: gateWayResponse.testOutcome,
                   resultTitle: gateWayResponse.resultTitle,
                   resultDescription: gateWayResponse.resultDescription,
                   resultLink: gateWayResponse.resultLink) {
                testResults.append(resultModel)
            }
        }
        */
        // 2) save the parent and pass the array saved above
        guard let context = managedContext else {return nil}
        /*
        let model = CovidLabTestResult(context: context)
        model.id = id
        model.name =
        model.phn =
        model.birthday =
        model.testDate =
        model.testId =
        model.resultDateTime =
        model.results = testResults
        model.user = fetchUser(id: userId)
        */
       
        
        return id
    }
    
    
    /// Store a test result
    /// - Returns: String id of record if stored successfully
    private func saveTestResult(
        resultId: String,
        patientDisplayName: String?,
        lab: String?,
        reportId: String?,
        collectionDateTime: Date?,
        resultDateTime: Date?,
        testName: String?,
        testType: String?,
        testStatus: String?,
        testOutcome: String?,
        resultTitle: String?,
        resultDescription: String?,
        resultLink: String?) -> TestResult? {
            guard let context = managedContext else {return nil}
            let testResult = TestResult(context: context)
            testResult.id = reportId
            testResult.patientDisplayName = patientDisplayName
            testResult.lab = lab
            testResult.reportId = reportId
            testResult.collectionDateTime = collectionDateTime
            testResult.resultDateTime = resultDateTime
            testResult.testName = testName
            testResult.testType = testType
            testResult.testStatus = testStatus
            testResult.testOutcome = testOutcome
            testResult.resultTitle = resultTitle
            testResult.resultDescription = resultDescription
            testResult.resultLink = resultLink
            do {
                try context.save()
                return testResult
            } catch let error as NSError {
                print("Could not save. \(error), \(error.userInfo)")
                return nil
            }
    }
    
    
    /// delete a test result for given id
    /// - Parameter id: id of record. this can be the report id or the id generated by during storage (TestResult.id)
    func deleteTestResult(id: String) {
        guard let context = managedContext else {return}
        do {
            let tests = try context.fetch(CovidLabTestResult.fetchRequest())
            guard let item = tests.filter({ ($0.id == id) || $0.testId == id}).first else {return}
            context.delete(item)
            try context.save()
        } catch let error as NSError {
            print("Could not delete. \(error), \(error.userInfo)")
            return
        }
    }
    
    /// Returns all test results stored for user
    /// - Parameter userId: User id. if left empty, the results results for the currently authenticated user.
    /// - Returns: All Test results stored for the given user
    func fetchTestResults(for userId: String? = AuthManager().userId()) -> [CovidLabTestResult] {
        guard let context = managedContext else {return []}
        do {
            let users = try context.fetch(User.fetchRequest())
            guard let current = users.filter({$0.userId == userId}).first else {return []}
            return current.testResultArray
        } catch let error as NSError {
            print("Could not fetch. \(error), \(error.userInfo)")
            return []
        }
    }
    
}
