# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'BCVaccineCard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCVaccineCard
  pod 'QueueITLibrary', '~> 3.0.3'
  pod "AlamofireRSSParser"

  target 'BCVaccineCardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BCVaccineCardUITests' do
    # Pods for testing
  end

end

target 'BCVaccineCard-Prod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCVaccineCard-Prod
  pod 'QueueITLibrary', '~> 3.0.3'
  pod "AlamofireRSSParser"
end
