# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'BCVaccineCard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCVaccineCard
  pod 'QueueITLibrary', '~> 3.0.3'
  pod "AlamofireRSSParser"
  pod 'SnowplowTracker', '~> 2.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase/AppDistribution'
  pod 'SwipeCellKit'
  pod 'SwiftQRCodeGenerator', '~> 1.0.3'
  pod 'PocketSVG', '~> 2.6'
  pod 'BCVaccineValidator', :git => 'https://github.com/bcgov/iOSVaccineValidator'
  pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git'
  pod 'KeychainAccess'
  pod 'AppAuth'
  pod 'JWTDecode', '~> 2.6'
  
  target 'BCVaccineCardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BCVaccineCardUITests' do
    # Pods for testing
  end

end

target 'BCVaccineCard-Prod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCVaccineCard-Prod
  pod 'QueueITLibrary', '~> 3.0.3'
  pod "AlamofireRSSParser"
  pod 'SnowplowTracker', '~> 2.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwipeCellKit'
  pod 'SwiftQRCodeGenerator', '~> 1.0.3'
  pod 'PocketSVG', '~> 2.6'
  pod 'BCVaccineValidator', :git => 'https://github.com/bcgov/iOSVaccineValidator'
  pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git'
  pod 'KeychainAccess'
  pod 'AppAuth'
  pod 'JWTDecode', '~> 2.6'
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
end
