name: Build Project
on:
  pull_request:
    branches:
      - dev-old
jobs:
  deploy:
    name: Building project
    runs-on: macOS-latest
    timeout-minutes: 25
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install gpg
        run: brew install gnupg
        
      - name: Setup profiles and certs
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
          FIREBASE_PROVISIONING: ${{ secrets.FIREBASE_PROVISIONING }}
        run: ./.github/secrets/decrypt_prod.sh
        
      - name: Select Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"
        
      - name: Build Dev target
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/build_dev.sh
        
      - name: Build Test target
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/build_test.sh
        
      - name: Build Prod target
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/build_prod.sh
