name: Build and deploy to TestFlight
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying to TestFlight
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Install gpg
        run: brew install gnupg
        
      - name: Select Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"
        
      - name: install xcpretty
        run: gem install xcpretty
        
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_dev.sh
        
      - name: Archive project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_dev.sh
        
      - name: Export .ipa
        run: ./.github/scripts/export_dev.sh
        
      - name: Upload to testflight
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/publish_testflight_dev.sh
        
      - name: Notify Slack - Success
        uses: act10ns/slack@v1
        with:
          status: Completed
          channel: 'bc-vaccine-card'
          message: New iOS build submitted to test-flight.
        
